version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      day: 'wednesday'
      interval: 'monthly'
      time: '02:00'
      timezone: 'Europe/Berlin'
  - package-ecosystem: npm
    directory: '/'
    schedule:
      day: 'wednesday'
      interval: 'monthly'
      time: '02:00'
      timezone: 'Europe/Berlin'
    open-pull-requests-limit: 99
    target-branch: main
    ignore:
      - dependency-name: 'husky'
        versions:
          - '>= 5'
      - dependency-name: '@types/node'
        versions:
          - '>= 17'
