name: 'CI'

on: [pull_request, push]

jobs:
  'Test':
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20.x]
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      - name: 'Use Node.js v${{ matrix.node-version }}'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: 'Install, lint, and test'
        run: |
          yarn install
          yarn test
        if: |
          contains(github.event.commits[0].message, '[skip ci]') == false &&
          contains(github.event.commits[0].message, '[ci skip]') == false
